"""Add location table

Revision ID: 38344deb45e0
Revises: 3ff9a25c3ee6
Create Date: 2024-11-04 03:23:08.978339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = '38344deb45e0'
down_revision: Union[str, None] = '3ff9a25c3ee6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('visitors', 'latitude',
               existing_type=mssql.REAL(),
               type_=sa.FLOAT(precision=6),
               existing_nullable=False)
    op.alter_column('visitors', 'longitude',
               existing_type=mssql.REAL(),
               type_=sa.FLOAT(precision=6),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('visitors', 'longitude',
               existing_type=sa.FLOAT(precision=6),
               type_=mssql.REAL(),
               existing_nullable=False)
    op.alter_column('visitors', 'latitude',
               existing_type=sa.FLOAT(precision=6),
               type_=mssql.REAL(),
               existing_nullable=False)
    # ### end Alembic commands ###
