"""Add ip address to Event analytic

Revision ID: 3ff9a25c3ee6
Revises: 180566b8801f
Create Date: 2024-04-25 20:58:45.380097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = '3ff9a25c3ee6'
down_revision: Union[str, None] = '180566b8801f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('ip_address', sa.String(length=15), nullable=False))
    op.alter_column('visitors', 'latitude',
               existing_type=mssql.REAL(),
               type_=sa.FLOAT(precision=6),
               existing_nullable=False)
    op.alter_column('visitors', 'longitude',
               existing_type=mssql.REAL(),
               type_=sa.FLOAT(precision=6),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('visitors', 'longitude',
               existing_type=sa.FLOAT(precision=6),
               type_=mssql.REAL(),
               existing_nullable=False)
    op.alter_column('visitors', 'latitude',
               existing_type=sa.FLOAT(precision=6),
               type_=mssql.REAL(),
               existing_nullable=False)
    op.drop_column('events', 'ip_address')
    # ### end Alembic commands ###
