"""Add analytics table

Revision ID: 4ab7860110c3
Revises: c30e2ba809af
Create Date: 2024-04-25 14:23:40.265345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ab7860110c3'
down_revision: Union[str, None] = 'c30e2ba809af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visitors',
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=15), nullable=False),
    sa.Column('country_code', sa.String(length=255), nullable=False),
    sa.Column('country_name', sa.String(length=255), nullable=False),
    sa.Column('region_name', sa.String(length=255), nullable=False),
    sa.Column('city_name', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.FLOAT(precision=6), nullable=False),
    sa.Column('longitude', sa.FLOAT(precision=6), nullable=False),
    sa.Column('zip_code', sa.INTEGER(), nullable=False),
    sa.Column('time_zone', sa.String(length=255), nullable=False),
    sa.Column('asn', sa.String(length=255), nullable=False),
    sa.Column('asn_name', sa.String(length=255), nullable=False),
    sa.Column('is_proxy', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['visitors.session_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    op.drop_table('visitors')
    # ### end Alembic commands ###
