"""Add comment field to Location model

Revision ID: 4ec8c4c9f7f8
Revises: b22a3d474536
Create Date: 2024-11-04 04:18:47.399725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = '4ec8c4c9f7f8'
down_revision: Union[str, None] = 'b22a3d474536'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location', sa.Column('comment', sa.Text(), nullable=True))
    op.alter_column('visitors', 'latitude',
               existing_type=mssql.REAL(),
               type_=sa.FLOAT(precision=6),
               existing_nullable=False)
    op.alter_column('visitors', 'longitude',
               existing_type=mssql.REAL(),
               type_=sa.FLOAT(precision=6),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('visitors', 'longitude',
               existing_type=sa.FLOAT(precision=6),
               type_=mssql.REAL(),
               existing_nullable=False)
    op.alter_column('visitors', 'latitude',
               existing_type=sa.FLOAT(precision=6),
               type_=mssql.REAL(),
               existing_nullable=False)
    op.drop_column('location', 'comment')
    # ### end Alembic commands ###
