"""Add created at for anlytic models

Revision ID: 60ef4eabd24f
Revises: 4ab7860110c3
Create Date: 2024-04-25 19:40:10.278602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = '60ef4eabd24f'
down_revision: Union[str, None] = '4ab7860110c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('created_at', sa.TIMESTAMP(), nullable=False))
    op.add_column('visitors', sa.Column('created_at', sa.TIMESTAMP(), nullable=False))
    op.alter_column('visitors', 'latitude',
               existing_type=mssql.REAL(),
               type_=sa.FLOAT(precision=6),
               existing_nullable=False)
    op.alter_column('visitors', 'longitude',
               existing_type=mssql.REAL(),
               type_=sa.FLOAT(precision=6),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('visitors', 'longitude',
               existing_type=sa.FLOAT(precision=6),
               type_=mssql.REAL(),
               existing_nullable=False)
    op.alter_column('visitors', 'latitude',
               existing_type=sa.FLOAT(precision=6),
               type_=mssql.REAL(),
               existing_nullable=False)
    op.drop_column('visitors', 'created_at')
    op.drop_column('events', 'created_at')
    # ### end Alembic commands ###
