"""fourth

Revision ID: 61b0c3fb2ae2
Revises: fad2afd0ebb7
Create Date: 2024-04-12 21:53:33.655748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61b0c3fb2ae2'
down_revision: Union[str, None] = 'fad2afd0ebb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'brand_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('FK__product__brand_i__2BFE89A6', 'product', type_='foreignkey')
    op.create_foreign_key(None, 'product', 'brand', ['brand_id'], ['id'], ondelete='NO ACTION')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.create_foreign_key('FK__product__brand_i__2BFE89A6', 'product', 'brand', ['brand_id'], ['id'], ondelete='CASCADE')
    op.alter_column('product', 'brand_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
