"""Add Lccation models

Revision ID: 78d39e8cb98c
Revises: 38344deb45e0
Create Date: 2024-11-04 03:37:03.190973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = '78d39e8cb98c'
down_revision: Union[str, None] = '38344deb45e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('phone_number', sa.String(length=255), nullable=True),
    sa.Column('area', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_id'), 'location', ['id'], unique=True)
    op.alter_column('visitors', 'latitude',
               existing_type=mssql.REAL(),
               type_=sa.FLOAT(precision=6),
               existing_nullable=False)
    op.alter_column('visitors', 'longitude',
               existing_type=mssql.REAL(),
               type_=sa.FLOAT(precision=6),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('visitors', 'longitude',
               existing_type=sa.FLOAT(precision=6),
               type_=mssql.REAL(),
               existing_nullable=False)
    op.alter_column('visitors', 'latitude',
               existing_type=sa.FLOAT(precision=6),
               type_=mssql.REAL(),
               existing_nullable=False)
    op.drop_index(op.f('ix_location_id'), table_name='location')
    op.drop_table('location')
    # ### end Alembic commands ###
