"""Add Location models 2

Revision ID: b22a3d474536
Revises: 78d39e8cb98c
Create Date: 2024-11-04 03:44:47.798717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = 'b22a3d474536'
down_revision: Union[str, None] = '78d39e8cb98c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('location', 'latitude',
               existing_type=sa.FLOAT(precision=53),
               type_=sa.Numeric(precision=30, scale=26),
               existing_nullable=False)
    op.alter_column('location', 'longitude',
               existing_type=sa.FLOAT(precision=53),
               type_=sa.Numeric(precision=31, scale=26),
               existing_nullable=False)
    op.alter_column('visitors', 'latitude',
               existing_type=mssql.REAL(),
               type_=sa.FLOAT(precision=6),
               existing_nullable=False)
    op.alter_column('visitors', 'longitude',
               existing_type=mssql.REAL(),
               type_=sa.FLOAT(precision=6),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('visitors', 'longitude',
               existing_type=sa.FLOAT(precision=6),
               type_=mssql.REAL(),
               existing_nullable=False)
    op.alter_column('visitors', 'latitude',
               existing_type=sa.FLOAT(precision=6),
               type_=mssql.REAL(),
               existing_nullable=False)
    op.alter_column('location', 'longitude',
               existing_type=sa.Numeric(precision=31, scale=26),
               type_=sa.FLOAT(precision=53),
               existing_nullable=False)
    op.alter_column('location', 'latitude',
               existing_type=sa.Numeric(precision=30, scale=26),
               type_=sa.FLOAT(precision=53),
               existing_nullable=False)
    # ### end Alembic commands ###
