"""no unique

Revision ID: c30e2ba809af
Revises: 61b0c3fb2ae2
Create Date: 2024-04-14 15:10:24.212025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c30e2ba809af'
down_revision: Union[str, None] = '61b0c3fb2ae2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'name',
               existing_type=sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
    op.alter_column('product', 'description',
               existing_type=sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
    op.alter_column('product', 'price',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index('ix_product_description', table_name='product')
    op.create_index(op.f('ix_product_description'), 'product', ['description'], unique=False)
    op.drop_index('ix_product_name', table_name='product')
    op.create_index(op.f('ix_product_name'), 'product', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_name'), table_name='product')
    op.create_index('ix_product_name', 'product', ['name'], unique=True)
    op.drop_index(op.f('ix_product_description'), table_name='product')
    op.create_index('ix_product_description', 'product', ['description'], unique=True)
    op.alter_column('product', 'price',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('product', 'description',
               existing_type=sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)
    op.alter_column('product', 'name',
               existing_type=sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)
    # ### end Alembic commands ###
