"""third

Revision ID: fad2afd0ebb7
Revises: 1e92127f9237
Create Date: 2024-04-12 21:43:46.059321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fad2afd0ebb7'
down_revision: Union[str, None] = '1e92127f9237'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('FK__product__brand_i__2645B050', 'product', type_='foreignkey')
    op.create_foreign_key(None, 'product', 'brand', ['brand_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.create_foreign_key('FK__product__brand_i__2645B050', 'product', 'brand', ['brand_id'], ['id'])
    # ### end Alembic commands ###
